# Generated by Django 3.2.7 on 2021-09-09 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_city_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='slug',
        ),
    ]
